ALTER TABLE payroll 
ADD COLUMN IF NOT EXISTS starting_cash_loan DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ending_cash_loan DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS starting_losses_damages DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ending_losses_damages DECIMAL(10, 2) DEFAULT 0;
