CREATE TABLE IF NOT EXISTS scratch_layer_data (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) DEFAULT 'Untitled',
    row_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
